[build]
builder = "nixpacks"

[deploy]
startCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan config:clear && php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100