[build]
builder = "nixpacks"
buildCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan reverb:start & php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on-failure"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
PHP_CLI_SERVER_WORKERS = "4"